---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-concourse
  - name: pcfawsops-terraform-state-get
params:
  PEM:
  ERT_DOMAIN:
run:
  path: aws-concourse/scripts/prepare-rds.sh
