---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalcfreleng/golang}

inputs:
  - name: aws-prepare-get
    path: go/src/github.com/c0-ops/aws-concourse
  - name: terraform_output

outputs:
  - name: bosh_configuration

run:
  path: go/src/github.com/c0-ops/aws-concourse/ci/tasks/generate-bosh-configuration/task.sh
