---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalcfreleng/golang}

inputs:
  - name: pcf-releng-ci
    path: go/src/github.com/c0-ops/aws-concourse
  - name: terraform_output
  - name: bosh_configuration

params:
  ERT_DOMAIN:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: go/src/github.com/c0-ops/aws-concourse/ci/tasks/configure-bosh/task.sh
